version: '3'
services:
  mysql:
    container_name: mysql_docker_php
    image: mysql:5.7
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../docker_db:/var/lib/mysql
  php:
    container_name: apache_docker_php
    build: ./apache
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
volumes:
  docker_db: